### ISSUE TITLE
Converting the flutter app to LIFF

### ISSUE THREAD

**Issue by shiki-tak** [Finschia/flutter-bird#6]

**Comment by Mdaiki0730** [comment]
There doesn't seem to be anything to be done in terms of development.
I have successfully converted my application to LIFF.
LIFF: https://liff.line.me/2005806035-vQq6OnZ1
App URL: https://flutter-bird.netlify.app

The LINE Messenger API allows us to receive URLs via LINE.
![image](https://github.com/Finschia/flutter-bird/assets/55307968/b4f6ac13-f167-4090-b4c2-0e4294845608)
